# Generated by Django 4.2.20 on 2025-04-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(default=0, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
