# Generated by Django 4.2.20 on 2025-04-20 07:07

from django.db import migrations
import hashlib


def calculate_hashes(apps, schema_editor):
    File = apps.get_model("files", "File")
    for file in File.objects.all():
        if not file.hash:
            with file.file.open("rb") as f:
                content = f.read()
                file.hash = hashlib.sha256(content).hexdigest()
                file.save(update_fields=["hash"])


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_file_hash"),
    ]

    operations = []
