# Generated by Django 4.2.20 on 2025-04-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_backfill_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
